# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    profile: "#{source_dir}/../profile"
    mysql: "#{source_dir}/../profile/spec/fixtures/modules/mysql"
    stdlib: "#{source_dir}/../profile/spec/fixtures/modules/stdlib"
    apache: "#{source_dir}/../profile/spec/fixtures/modules/apache"
    concat: "#{source_dir}/../profile/spec/fixtures/modules/concat"
    gitea: "#{source_dir}/../profile/spec/fixtures/modules/gitea"
    inifile: "#{source_dir}/../profile/spec/fixtures/modules/inifile"
    archive: "#{source_dir}/../profile/spec/fixtures/modules/archive"
    extlib: "#{source_dir}/../profile/spec/fixtures/modules/extlib"
    systemd: "#{source_dir}/../profile/spec/fixtures/modules/systemd"
