# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    mysql: 
      repo: "puppetlabs/mysql"
    stdlib: 
      repo: "puppetlabs/stdlib"
    apache: 
      repo: "puppetlabs/apache"
    concat: 
      repo: "puppetlabs/concat"
    gitea: 
      repo: "h0tw1r3/gitea"
      ref: "3.3.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "6.2.0"
    archive:
      repo: "puppet/archive"
      ref: "7.1.0"
    extlib:
      repo: "puppet/extlib"
      ref: "7.3.0"
    systemd:
      repo: "puppet/systemd"
      ref: "8.1.0"
